"""Assemble the final kg_split_benchmark_report.md from the per-corpus tables.

Sections:
  1. Headline summary (the H1/H2/H3/H4 hypotheses from the protocol)
  2. Per-corpus Stage 1/2/3 status
  3. Mode A split-quality (per-target means) per corpus
  4. Mode B split-quality (pooled) per corpus
  5. Mode A model metrics
  6. Mode B model metrics
  7. Per-axis residual decomposition
  8. Stat tests
  9. Splitters skipped / failed / solver-limited per corpus
"""
from __future__ import annotations
import argparse
from pathlib import Path
import polars as pl


def fmt(v, n=4) -> str:
    try:
        f = float(v)
        if f != f:  # NaN
            return "—"
        return f"{f:.{n}f}"
    except Exception:
        return str(v)


def read_table(path: Path) -> pl.DataFrame:
    if not path.exists():
        return pl.DataFrame()
    return pl.read_csv(path, infer_schema_length=0)


def section_mode_quality(corpus: str, mode: str, df: pl.DataFrame) -> str:
    if df.height == 0:
        return f"### {corpus} Mode {mode} — split-quality\n_(no rows)_\n\n"
    # Per-(splitter) aggregate across targets.
    agg = (df.group_by("splitter")
             .agg([
                 pl.col("n_test").cast(pl.Float64).mean().alias("n_test_mean"),
                 pl.col("c_total_mean").cast(pl.Float64, strict=False).mean().alias("c_total"),
                 pl.col("max_lig_tanimoto").cast(pl.Float64, strict=False).mean().alias("max_lig"),
                 pl.col("c_ligand").alias("c_lig_sample"),
                 pl.col("c_protein").alias("c_prot_sample"),
             ])
             .sort("c_total")
    )
    lines = [f"### {corpus} Mode {mode} — split-quality (mean over targets)\n",
             "| Splitter | mean n_test | c_total | max ligand Tanimoto |",
             "|---|---:|---:|---:|"]
    for r in agg.iter_rows(named=True):
        lines.append(f"| {r['splitter']} | {r['n_test_mean']:.0f} | {fmt(r['c_total'])} | {fmt(r['max_lig'])} |")
    return "\n".join(lines) + "\n\n"


def section_model(corpus: str, mode: str, df: pl.DataFrame) -> str:
    if df.height == 0:
        return f"### {corpus} Mode {mode} — model metrics\n_(no rows)_\n\n"
    agg = (df.filter(pl.col("model") == "morgan_rf")
             .group_by("splitter")
             .agg([
                 pl.col("auroc").cast(pl.Float64, strict=False).mean().alias("auroc"),
                 pl.col("ef1pct").cast(pl.Float64, strict=False).mean().alias("ef1pct"),
                 pl.col("bedroc").cast(pl.Float64, strict=False).mean().alias("bedroc"),
             ])
             .sort("auroc"))
    lines = [f"### {corpus} Mode {mode} — Morgan-RF AUROC / EF1% / BEDROC (mean over targets)\n",
             "| Splitter | AUROC | EF1% | BEDROC |",
             "|---|---:|---:|---:|"]
    for r in agg.iter_rows(named=True):
        lines.append(f"| {r['splitter']} | {fmt(r['auroc'])} | {fmt(r['ef1pct'], 2)} | {fmt(r['bedroc'])} |")
    return "\n".join(lines) + "\n\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", default=Path("outputs/splits_review"), type=Path)
    ap.add_argument("--out",  default=Path("outputs/reports/splits_review/kg_split_benchmark_report.md"),
                    type=Path)
    args = ap.parse_args()

    parts = ["# KG vs split-frameworks benchmark — report\n\n",
             "Auto-generated by `tools/splits_review/build_report.py`. Source tables under "
             "`outputs/splits_review/<corpus>/data/`.\n\n",
             "## Pre-registered hypotheses (from kg_split_benchmark_protocol.md)\n\n",
             "- **H1** residual contamination: KG < every non-KG splitter on c_total.\n",
             "- **H2** shortcut performance: KG < AVE/DataSAIL on Morgan-RF AUROC AND 1-NN AUROC AND C-NN AUROC.\n",
             "- **H3** per-axis residual decomposition: KG produces per-axis profile no external framework offers.\n",
             "- **H4** path attribution: KG names the dominant axis per test pair.\n\n"]

    for corpus in ("litpcba", "dekois", "dude"):
        cdir = args.root / corpus / "data"
        if not cdir.exists():
            parts.append(f"## {corpus.upper()} — NOT RUN\n\n")
            continue
        parts.append(f"## {corpus.upper()}\n\n")
        parts.append(section_mode_quality(corpus, "A", read_table(cdir / "table_split_quality_modeA.csv")))
        parts.append(section_mode_quality(corpus, "B", read_table(cdir / "table_split_quality_modeB.csv")))
        parts.append(section_model(corpus, "A", read_table(cdir / "table_split_modelmetrics_modeA.csv")))
        parts.append(section_model(corpus, "B", read_table(cdir / "table_split_modelmetrics_modeB.csv")))

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("".join(parts))
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
